### ISSUE TITLE
Añadir canales autonomicos

### ISSUE THREAD

**Issue by aikrana** [MPAndrew/EpgGratis#1]
Fantástico repo. ¿Sería posible añadir canales autonómicos como À Punt? 
Logo: http://www.movistarplus.es/recorte/m-NEO/guiapc/APUNT.png
Id: APUNT

**Comment by MPAndrew** [comment]
Acabo de leerte, no se por qué no me ha llegado la notificación al correo. Canal añadido, si hay alguno más dímelo por aquí y lo pongo también.

Saludos.

**Comment by aikrana** [comment]
Gracias!
